
CREATE TABLE movie_metadata (
    color VARCHAR(20),
    director_name VARCHAR(100),
    num_critic_for_reviews INT,
    duration INT,
    director_facebook_likes INT,
    actor_3_facebook_likes INT,
    actor_2_name VARCHAR(100),
    actor_1_facebook_likes INT,
    gross BIGINT,
    genres VARCHAR(255),
    actor_1_name VARCHAR(100),
    movie_title VARCHAR(255),
    num_voted_users INT,
    cast_total_facebook_likes INT,
    actor_3_name VARCHAR(100),
    facenumber_in_poster INT,
    plot_keywords TEXT,
    movie_imdb_link VARCHAR(255),
    num_user_for_reviews INT,
    language VARCHAR(50),
    country VARCHAR(50),
    content_rating VARCHAR(50),
    budget BIGINT,
    title_year INT,
    actor_2_facebook_likes INT,
    imdb_score FLOAT,
    aspect_ratio FLOAT,
    movie_facebook_likes INT
);
